technology:
  wire_cap: 1e-12
  sense_amp_time: 1e-9
  plogic_node: 40
voltage: 1
memory_levels: 2
memory:
  level0:
    class: SRAM
    frequency: 1000
    banks: 4
    read_ports: 1
    write_ports: 1
    width: 32
    size: 1000000
  level1:
    class: DRAM
    frequency: 5
    banks: 5
    read_ports: 1
    write_ports: 1
    width: 2
    size: 100000000000
mm_compute:
  class: systolic_array
  frequency: 1000
  size: 64
  N_PE: 4
vector_compute:
  class: systolic_array
  frequency: 1000
  size: 64
  N_PE: 4
