memory_levels: 2
memory:
  level0:
    class: SRAM
    frequency: 1000
    banks: 4
    read_ports: 1
    write_ports: 1
    width: 32
    size: 1000000
  level1:
    class: DRAM
    frequency: 5
    banks: 2
    read_ports: 1
    write_ports: 1
    width: 2
    size: 100000000000
  local_mem:
    type: 1
      class: SRAM
      size: 512
    type: 2
      class: SRAM
      size: 2048
mm_compute:
  type: 1
    class: systolic_array
    frequency: 1000
    size: 64
    N_PE: 1
  type: 2
    class: mac
    frequency: 1000
    size: 1
    N_PE: 256

