technology: 40nm
voltage: 1
memory_levels: 2
memory:
  level0:
    class: SRAM
    frequency: 1000
    banks: 4
    read_ports: 1
    write_ports: 1
    width: 32
    size: 129377
  level1:
    class: DRAM
    frequency: 100
    banks: 6
    read_ports: 1
    write_ports: 1
    width: 64
    size: 100000000000
mm_compute:
  class: systolic_array
  frequency: 1000
  size: 256
  N_PE: 4
vector_compute:
  class: systolic_array
  frequency: 1000
  size: 256
  N_PE: 1
mm_compute_per_cycle: 131072.0
comp_bw: 2048000
