sytolic_array:
  size: 24

sram_memory:
  size: 25000
  area: 100000
  latency: 200
  energy: 6000
  connectivity: 300

dram_memory:
  size: 30000000
  area:
  latency: 400
  connectivity: 800

registerfile:
  size:
  area:
  latency:
  connectivity:
